// Code generated by generator, DO NOT EDIT.
package trcache

import "time"

func WithMetrics[K comparable, V any](metrics Metrics, name string) RootOption {
	return RootOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case Options[K, V]:
			opt.OptMetrics(metrics, name)
			return true
		}
		return false
	})
}
func WithCallDefaultDeleteOptions[K comparable, V any](options ...DeleteOption) RootOption {
	return RootOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case CallDefaultOptions[K, V]:
			opt.OptCallDefaultDeleteOptions(options...)
			return true
		}
		return false
	})
}
func WithCallDefaultGetOptions[K comparable, V any](options ...GetOption) RootOption {
	return RootOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case CallDefaultOptions[K, V]:
			opt.OptCallDefaultGetOptions(options...)
			return true
		}
		return false
	})
}
func WithCallDefaultSetOptions[K comparable, V any](options ...SetOption) RootOption {
	return RootOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case CallDefaultOptions[K, V]:
			opt.OptCallDefaultSetOptions(options...)
			return true
		}
		return false
	})
}
func WithCallDefaultRefreshOptions[K comparable, V any](options ...RefreshOption) RootOption {
	return RootOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case CallDefaultRefreshOptions[K, V]:
			opt.OptCallDefaultRefreshOptions(options...)
			return true
		}
		return false
	})
}
func WithGetCustomOptions[K comparable, V any](customOptions []interface{}) GetOption {
	return GetOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case GetOptions[K, V]:
			opt.OptCustomOptions(customOptions)
			return true
		}
		return false
	})
}
func WithSetDuration[K comparable, V any](duration time.Duration) SetOption {
	return SetOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case SetOptions[K, V]:
			opt.OptDuration(duration)
			return true
		}
		return false
	})
}
func WithRefreshData[K comparable, V any](data interface{}) RefreshOption {
	return RefreshOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case RefreshOptions[K, V]:
			opt.OptData(data)
			return true
		}
		return false
	})
}
func WithRefreshRefreshFunc[K comparable, V any](refreshFunc CacheRefreshFunc[K, V]) RefreshOption {
	return RefreshOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case RefreshOptions[K, V]:
			opt.OptRefreshFunc(refreshFunc)
			return true
		}
		return false
	})
}
func WithRefreshSetOptions[K comparable, V any](options ...SetOption) RefreshOption {
	return RefreshOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case RefreshOptions[K, V]:
			opt.OptSetOptions(options...)
			return true
		}
		return false
	})
}

type rootOptionBuilder[K comparable, V any] struct {
	RootOptionBuilderBase
}

func RootOpt[K comparable, V any]() *rootOptionBuilder[K, V] {
	return &rootOptionBuilder[K, V]{}
}
func (ob *rootOptionBuilder[K, V]) WithMetrics(metrics Metrics, name string) *rootOptionBuilder[K, V] {
	ob.AppendOptions(WithMetrics[K, V](metrics, name))
	return ob
}
func (ob *rootOptionBuilder[K, V]) WithCallDefaultDeleteOptions(options ...DeleteOption) *rootOptionBuilder[K, V] {
	ob.AppendOptions(WithCallDefaultDeleteOptions[K, V](options...))
	return ob
}
func (ob *rootOptionBuilder[K, V]) WithCallDefaultGetOptions(options ...GetOption) *rootOptionBuilder[K, V] {
	ob.AppendOptions(WithCallDefaultGetOptions[K, V](options...))
	return ob
}
func (ob *rootOptionBuilder[K, V]) WithCallDefaultSetOptions(options ...SetOption) *rootOptionBuilder[K, V] {
	ob.AppendOptions(WithCallDefaultSetOptions[K, V](options...))
	return ob
}
func (ob *rootOptionBuilder[K, V]) WithCallDefaultRefreshOptions(options ...RefreshOption) *rootOptionBuilder[K, V] {
	ob.AppendOptions(WithCallDefaultRefreshOptions[K, V](options...))
	return ob
}

type getOptionBuilder[K comparable, V any] struct {
	GetOptionBuilderBase
}

func GetOpt[K comparable, V any]() *getOptionBuilder[K, V] {
	return &getOptionBuilder[K, V]{}
}
func (ob *getOptionBuilder[K, V]) WithGetCustomOptions(customOptions []interface{}) *getOptionBuilder[K, V] {
	ob.AppendOptions(WithGetCustomOptions[K, V](customOptions))
	return ob
}

type setOptionBuilder[K comparable, V any] struct {
	SetOptionBuilderBase
}

func SetOpt[K comparable, V any]() *setOptionBuilder[K, V] {
	return &setOptionBuilder[K, V]{}
}
func (ob *setOptionBuilder[K, V]) WithSetDuration(duration time.Duration) *setOptionBuilder[K, V] {
	ob.AppendOptions(WithSetDuration[K, V](duration))
	return ob
}

type refreshOptionBuilder[K comparable, V any] struct {
	RefreshOptionBuilderBase
}

func RefreshOpt[K comparable, V any]() *refreshOptionBuilder[K, V] {
	return &refreshOptionBuilder[K, V]{}
}
func (ob *refreshOptionBuilder[K, V]) WithRefreshData(data interface{}) *refreshOptionBuilder[K, V] {
	ob.AppendOptions(WithRefreshData[K, V](data))
	return ob
}
func (ob *refreshOptionBuilder[K, V]) WithRefreshRefreshFunc(refreshFunc CacheRefreshFunc[K, V]) *refreshOptionBuilder[K, V] {
	ob.AppendOptions(WithRefreshRefreshFunc[K, V](refreshFunc))
	return ob
}
func (ob *refreshOptionBuilder[K, V]) WithRefreshSetOptions(options ...SetOption) *refreshOptionBuilder[K, V] {
	ob.AppendOptions(WithRefreshSetOptions[K, V](options...))
	return ob
}
