// Code generated by troptgen. DO NOT EDIT.

package trcache

import "time"

func WithName[K comparable, V any](name string) RootOption {
	const optionName = "github.com/RangelReale/trcache/NameOptions.Name"
	const optionHash = uint64(0x98d6a600b692b726)
	return RootOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case NameOptions[K, V]:
			opt.OptName(name)
			return true
		}
		return false
	}, optionName, optionHash)
}
func WithMetrics[K comparable, V any](metrics Metrics, name string) RootOption {
	const optionName = "github.com/RangelReale/trcache/MetricsOptions.Metrics"
	const optionHash = uint64(0x1beb63d6b36d066c)
	return RootOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case MetricsOptions[K, V]:
			opt.OptMetrics(metrics, name)
			return true
		}
		return false
	}, optionName, optionHash)
}
func WithCallDefaultDeleteOptions[K comparable, V any](options ...DeleteOption) RootOption {
	const optionName = "github.com/RangelReale/trcache/CallDefaultOptions.CallDefaultDeleteOptions"
	const optionHash = uint64(0x406b2f02562353ed)
	return RootOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case CallDefaultOptions[K, V]:
			opt.OptCallDefaultDeleteOptions(options...)
			return true
		}
		return false
	}, optionName, optionHash)
}
func WithCallDefaultGetOptions[K comparable, V any](options ...GetOption) RootOption {
	const optionName = "github.com/RangelReale/trcache/CallDefaultOptions.CallDefaultGetOptions"
	const optionHash = uint64(0x22e5cf931cff25e)
	return RootOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case CallDefaultOptions[K, V]:
			opt.OptCallDefaultGetOptions(options...)
			return true
		}
		return false
	}, optionName, optionHash)
}
func WithCallDefaultSetOptions[K comparable, V any](options ...SetOption) RootOption {
	const optionName = "github.com/RangelReale/trcache/CallDefaultOptions.CallDefaultSetOptions"
	const optionHash = uint64(0xbe5b3492dd589c42)
	return RootOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case CallDefaultOptions[K, V]:
			opt.OptCallDefaultSetOptions(options...)
			return true
		}
		return false
	}, optionName, optionHash)
}
func WithCallDefaultRefreshOptions[K comparable, V any](options ...RefreshOption) RootOption {
	const optionName = "github.com/RangelReale/trcache/CallDefaultRefreshOptions.CallDefaultRefreshOptions"
	const optionHash = uint64(0x1ff4089053065e4c)
	return RootOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case CallDefaultRefreshOptions[K, V]:
			opt.OptCallDefaultRefreshOptions(options...)
			return true
		}
		return false
	}, optionName, optionHash)
}
func WithSetDuration[K comparable, V any](duration time.Duration) SetOption {
	const optionName = "github.com/RangelReale/trcache/SetOptions.Duration"
	const optionHash = uint64(0x4782e16ce757eefa)
	return SetOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case SetOptions[K, V]:
			opt.OptDuration(duration)
			return true
		}
		return false
	}, optionName, optionHash)
}
func WithRefreshData[K comparable, V any, RD any](data RD) RefreshOption {
	const optionName = "github.com/RangelReale/trcache/RefreshOptions.Data"
	const optionHash = uint64(0x15f36f99082ff0db)
	return RefreshOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case RefreshOptions[K, V, RD]:
			opt.OptData(data)
			return true
		}
		return false
	}, optionName, optionHash)
}
func WithRefreshFunc[K comparable, V any, RD any](refreshFunc CacheRefreshFunc[K, V, RD]) RefreshOption {
	const optionName = "github.com/RangelReale/trcache/RefreshOptions.Func"
	const optionHash = uint64(0x27dba799127e8249)
	return RefreshOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case RefreshOptions[K, V, RD]:
			opt.OptFunc(refreshFunc)
			return true
		}
		return false
	}, optionName, optionHash)
}
func WithRefreshGetOptions[K comparable, V any, RD any](options ...GetOption) RefreshOption {
	const optionName = "github.com/RangelReale/trcache/RefreshOptions.GetOptions"
	const optionHash = uint64(0x8991bcf58fe8472d)
	return RefreshOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case RefreshOptions[K, V, RD]:
			opt.OptGetOptions(options...)
			return true
		}
		return false
	}, optionName, optionHash)
}
func WithRefreshSetOptions[K comparable, V any, RD any](options ...SetOption) RefreshOption {
	const optionName = "github.com/RangelReale/trcache/RefreshOptions.SetOptions"
	const optionHash = uint64(0x67f5357186bd5f31)
	return RefreshOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case RefreshOptions[K, V, RD]:
			opt.OptSetOptions(options...)
			return true
		}
		return false
	}, optionName, optionHash)
}
func WithDefaultRefreshFunc[K comparable, V any, RD any](refreshFunc CacheRefreshFunc[K, V, RD]) RootOption {
	const optionName = "github.com/RangelReale/trcache/DefaultRefreshOptions.DefaultRefreshFunc"
	const optionHash = uint64(0x11a5dca1c92613ac)
	return RootOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case DefaultRefreshOptions[K, V, RD]:
			opt.OptDefaultRefreshFunc(refreshFunc)
			return true
		}
		return false
	}, optionName, optionHash)
}
