// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	context "context"

	trcache "github.com/RangelReale/trcache"
	mock "github.com/stretchr/testify/mock"
)

// RefreshCache is an autogenerated mock type for the RefreshCache type
type RefreshCache[K comparable, V interface{}, RD interface{}] struct {
	mock.Mock
}

type RefreshCache_Expecter[K comparable, V interface{}, RD interface{}] struct {
	mock *mock.Mock
}

func (_m *RefreshCache[K, V, RD]) EXPECT() *RefreshCache_Expecter[K, V, RD] {
	return &RefreshCache_Expecter[K, V, RD]{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, key, options
func (_m *RefreshCache[K, V, RD]) Delete(ctx context.Context, key K, options ...trcache.DeleteOption) error {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, key)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, K, ...trcache.DeleteOption) error); ok {
		r0 = rf(ctx, key, options...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshCache_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type RefreshCache_Delete_Call[K comparable, V interface{}, RD interface{}] struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key K
//   - options ...trcache.DeleteOption
func (_e *RefreshCache_Expecter[K, V, RD]) Delete(ctx interface{}, key interface{}, options ...interface{}) *RefreshCache_Delete_Call[K, V, RD] {
	return &RefreshCache_Delete_Call[K, V, RD]{Call: _e.mock.On("Delete",
		append([]interface{}{ctx, key}, options...)...)}
}

func (_c *RefreshCache_Delete_Call[K, V, RD]) Run(run func(ctx context.Context, key K, options ...trcache.DeleteOption)) *RefreshCache_Delete_Call[K, V, RD] {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]trcache.DeleteOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(trcache.DeleteOption)
			}
		}
		run(args[0].(context.Context), args[1].(K), variadicArgs...)
	})
	return _c
}

func (_c *RefreshCache_Delete_Call[K, V, RD]) Return(_a0 error) *RefreshCache_Delete_Call[K, V, RD] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RefreshCache_Delete_Call[K, V, RD]) RunAndReturn(run func(context.Context, K, ...trcache.DeleteOption) error) *RefreshCache_Delete_Call[K, V, RD] {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, key, options
func (_m *RefreshCache[K, V, RD]) Get(ctx context.Context, key K, options ...trcache.GetOption) (V, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, key)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 V
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, K, ...trcache.GetOption) (V, error)); ok {
		return rf(ctx, key, options...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, K, ...trcache.GetOption) V); ok {
		r0 = rf(ctx, key, options...)
	} else {
		r0 = ret.Get(0).(V)
	}

	if rf, ok := ret.Get(1).(func(context.Context, K, ...trcache.GetOption) error); ok {
		r1 = rf(ctx, key, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RefreshCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type RefreshCache_Get_Call[K comparable, V interface{}, RD interface{}] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key K
//   - options ...trcache.GetOption
func (_e *RefreshCache_Expecter[K, V, RD]) Get(ctx interface{}, key interface{}, options ...interface{}) *RefreshCache_Get_Call[K, V, RD] {
	return &RefreshCache_Get_Call[K, V, RD]{Call: _e.mock.On("Get",
		append([]interface{}{ctx, key}, options...)...)}
}

func (_c *RefreshCache_Get_Call[K, V, RD]) Run(run func(ctx context.Context, key K, options ...trcache.GetOption)) *RefreshCache_Get_Call[K, V, RD] {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]trcache.GetOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(trcache.GetOption)
			}
		}
		run(args[0].(context.Context), args[1].(K), variadicArgs...)
	})
	return _c
}

func (_c *RefreshCache_Get_Call[K, V, RD]) Return(_a0 V, _a1 error) *RefreshCache_Get_Call[K, V, RD] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RefreshCache_Get_Call[K, V, RD]) RunAndReturn(run func(context.Context, K, ...trcache.GetOption) (V, error)) *RefreshCache_Get_Call[K, V, RD] {
	_c.Call.Return(run)
	return _c
}

// GetOrRefresh provides a mock function with given fields: ctx, key, options
func (_m *RefreshCache[K, V, RD]) GetOrRefresh(ctx context.Context, key K, options ...trcache.RefreshOption) (V, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, key)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 V
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, K, ...trcache.RefreshOption) (V, error)); ok {
		return rf(ctx, key, options...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, K, ...trcache.RefreshOption) V); ok {
		r0 = rf(ctx, key, options...)
	} else {
		r0 = ret.Get(0).(V)
	}

	if rf, ok := ret.Get(1).(func(context.Context, K, ...trcache.RefreshOption) error); ok {
		r1 = rf(ctx, key, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RefreshCache_GetOrRefresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrRefresh'
type RefreshCache_GetOrRefresh_Call[K comparable, V interface{}, RD interface{}] struct {
	*mock.Call
}

// GetOrRefresh is a helper method to define mock.On call
//   - ctx context.Context
//   - key K
//   - options ...trcache.RefreshOption
func (_e *RefreshCache_Expecter[K, V, RD]) GetOrRefresh(ctx interface{}, key interface{}, options ...interface{}) *RefreshCache_GetOrRefresh_Call[K, V, RD] {
	return &RefreshCache_GetOrRefresh_Call[K, V, RD]{Call: _e.mock.On("GetOrRefresh",
		append([]interface{}{ctx, key}, options...)...)}
}

func (_c *RefreshCache_GetOrRefresh_Call[K, V, RD]) Run(run func(ctx context.Context, key K, options ...trcache.RefreshOption)) *RefreshCache_GetOrRefresh_Call[K, V, RD] {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]trcache.RefreshOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(trcache.RefreshOption)
			}
		}
		run(args[0].(context.Context), args[1].(K), variadicArgs...)
	})
	return _c
}

func (_c *RefreshCache_GetOrRefresh_Call[K, V, RD]) Return(_a0 V, _a1 error) *RefreshCache_GetOrRefresh_Call[K, V, RD] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RefreshCache_GetOrRefresh_Call[K, V, RD]) RunAndReturn(run func(context.Context, K, ...trcache.RefreshOption) (V, error)) *RefreshCache_GetOrRefresh_Call[K, V, RD] {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with given fields:
func (_m *RefreshCache[K, V, RD]) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// RefreshCache_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type RefreshCache_Name_Call[K comparable, V interface{}, RD interface{}] struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *RefreshCache_Expecter[K, V, RD]) Name() *RefreshCache_Name_Call[K, V, RD] {
	return &RefreshCache_Name_Call[K, V, RD]{Call: _e.mock.On("Name")}
}

func (_c *RefreshCache_Name_Call[K, V, RD]) Run(run func()) *RefreshCache_Name_Call[K, V, RD] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RefreshCache_Name_Call[K, V, RD]) Return(_a0 string) *RefreshCache_Name_Call[K, V, RD] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RefreshCache_Name_Call[K, V, RD]) RunAndReturn(run func() string) *RefreshCache_Name_Call[K, V, RD] {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, key, value, options
func (_m *RefreshCache[K, V, RD]) Set(ctx context.Context, key K, value V, options ...trcache.SetOption) error {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, key, value)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, K, V, ...trcache.SetOption) error); ok {
		r0 = rf(ctx, key, value, options...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type RefreshCache_Set_Call[K comparable, V interface{}, RD interface{}] struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key K
//   - value V
//   - options ...trcache.SetOption
func (_e *RefreshCache_Expecter[K, V, RD]) Set(ctx interface{}, key interface{}, value interface{}, options ...interface{}) *RefreshCache_Set_Call[K, V, RD] {
	return &RefreshCache_Set_Call[K, V, RD]{Call: _e.mock.On("Set",
		append([]interface{}{ctx, key, value}, options...)...)}
}

func (_c *RefreshCache_Set_Call[K, V, RD]) Run(run func(ctx context.Context, key K, value V, options ...trcache.SetOption)) *RefreshCache_Set_Call[K, V, RD] {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]trcache.SetOption, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(trcache.SetOption)
			}
		}
		run(args[0].(context.Context), args[1].(K), args[2].(V), variadicArgs...)
	})
	return _c
}

func (_c *RefreshCache_Set_Call[K, V, RD]) Return(_a0 error) *RefreshCache_Set_Call[K, V, RD] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RefreshCache_Set_Call[K, V, RD]) RunAndReturn(run func(context.Context, K, V, ...trcache.SetOption) error) *RefreshCache_Set_Call[K, V, RD] {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewRefreshCache interface {
	mock.TestingT
	Cleanup(func())
}

// NewRefreshCache creates a new instance of RefreshCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRefreshCache[K comparable, V interface{}, RD interface{}](t mockConstructorTestingTNewRefreshCache) *RefreshCache[K, V, RD] {
	mock := &RefreshCache[K, V, RD]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
