// Code generated by generator, DO NOT EDIT.
package trttlcache

import (
	trcache "github.com/RangelReale/trcache"
	"time"
)

func WithCallDefaultDeleteOptions[K comparable, V any](p0 ...trcache.DeleteOption) trcache.RootOption {
	return trcache.RootOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case Options[K, V]:
			opt.OptCallDefaultDeleteOptions(p0...)
			return true
		}
		return false
	})
}
func WithCallDefaultGetOptions[K comparable, V any](p0 ...trcache.GetOption) trcache.RootOption {
	return trcache.RootOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case Options[K, V]:
			opt.OptCallDefaultGetOptions(p0...)
			return true
		}
		return false
	})
}
func WithCallDefaultSetOptions[K comparable, V any](p0 ...trcache.SetOption) trcache.RootOption {
	return trcache.RootOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case Options[K, V]:
			opt.OptCallDefaultSetOptions(p0...)
			return true
		}
		return false
	})
}
func WithDefaultDuration[K comparable, V any](p0 time.Duration) trcache.RootOption {
	return trcache.RootOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case Options[K, V]:
			opt.OptDefaultDuration(p0)
			return true
		}
		return false
	})
}
func WithName[K comparable, V any](p0 string) trcache.RootOption {
	return trcache.RootOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case Options[K, V]:
			opt.OptName(p0)
			return true
		}
		return false
	})
}
func WithValidator[K comparable, V any](p0 trcache.Validator[V]) trcache.RootOption {
	return trcache.RootOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case Options[K, V]:
			opt.OptValidator(p0)
			return true
		}
		return false
	})
}
func WithGetCustomOptions[K comparable, V any](p0 []interface{}) trcache.GetOption {
	return trcache.GetOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case GetOptions[K, V]:
			opt.OptCustomOptions(p0)
			return true
		}
		return false
	})
}
func WithGetTouch[K comparable, V any](p0 bool) trcache.GetOption {
	return trcache.GetOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case GetOptions[K, V]:
			opt.OptTouch(p0)
			return true
		}
		return false
	})
}
func WithSetDuration[K comparable, V any](p0 time.Duration) trcache.SetOption {
	return trcache.SetOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case SetOptions[K, V]:
			opt.OptDuration(p0)
			return true
		}
		return false
	})
}

type RootOptionBuilder[K comparable, V any] struct {
	trcache.RootOptionBuilderBase
}

func RootOpt[K comparable, V any]() *RootOptionBuilder[K, V] {
	return &RootOptionBuilder[K, V]{}
}
func (ob *RootOptionBuilder[K, V]) WithCallDefaultDeleteOptions(p0 ...trcache.DeleteOption) *RootOptionBuilder[K, V] {
	ob.AppendOptions(WithCallDefaultDeleteOptions[K, V](p0...))
	return ob
}
func (ob *RootOptionBuilder[K, V]) WithCallDefaultGetOptions(p0 ...trcache.GetOption) *RootOptionBuilder[K, V] {
	ob.AppendOptions(WithCallDefaultGetOptions[K, V](p0...))
	return ob
}
func (ob *RootOptionBuilder[K, V]) WithCallDefaultSetOptions(p0 ...trcache.SetOption) *RootOptionBuilder[K, V] {
	ob.AppendOptions(WithCallDefaultSetOptions[K, V](p0...))
	return ob
}
func (ob *RootOptionBuilder[K, V]) WithDefaultDuration(p0 time.Duration) *RootOptionBuilder[K, V] {
	ob.AppendOptions(WithDefaultDuration[K, V](p0))
	return ob
}
func (ob *RootOptionBuilder[K, V]) WithName(p0 string) *RootOptionBuilder[K, V] {
	ob.AppendOptions(WithName[K, V](p0))
	return ob
}
func (ob *RootOptionBuilder[K, V]) WithValidator(p0 trcache.Validator[V]) *RootOptionBuilder[K, V] {
	ob.AppendOptions(WithValidator[K, V](p0))
	return ob
}

type GetOptionBuilder[K comparable, V any] struct {
	trcache.GetOptionBuilderBase
}

func GetOpt[K comparable, V any]() *GetOptionBuilder[K, V] {
	return &GetOptionBuilder[K, V]{}
}
func (ob *GetOptionBuilder[K, V]) WithGetCustomOptions(p0 []interface{}) *GetOptionBuilder[K, V] {
	ob.AppendOptions(WithGetCustomOptions[K, V](p0))
	return ob
}
func (ob *GetOptionBuilder[K, V]) WithGetTouch(p0 bool) *GetOptionBuilder[K, V] {
	ob.AppendOptions(WithGetTouch[K, V](p0))
	return ob
}

type SetOptionBuilder[K comparable, V any] struct {
	trcache.SetOptionBuilderBase
}

func SetOpt[K comparable, V any]() *SetOptionBuilder[K, V] {
	return &SetOptionBuilder[K, V]{}
}
func (ob *SetOptionBuilder[K, V]) WithSetDuration(p0 time.Duration) *SetOptionBuilder[K, V] {
	ob.AppendOptions(WithSetDuration[K, V](p0))
	return ob
}

type DeleteOptionBuilder[K comparable, V any] struct {
	trcache.DeleteOptionBuilderBase
}

func DeleteOpt[K comparable, V any]() *DeleteOptionBuilder[K, V] {
	return &DeleteOptionBuilder[K, V]{}
}
