// Code generated by generator, DO NOT EDIT.
package chain

import (
	trcache "github.com/RangelReale/trcache"
	"time"
)

func WithRefreshFunc[K comparable, V any](refreshFunc trcache.CacheRefreshFunc[K, V]) trcache.RootOption {
	return trcache.RootOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case options[K, V]:
			opt.OptRefreshFunc(refreshFunc)
			return true
		}
		return false
	})
}
func WithSetPreviousOnGet[K comparable, V any](setPreviousOnGet bool) trcache.RootOption {
	return trcache.RootOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case options[K, V]:
			opt.OptSetPreviousOnGet(setPreviousOnGet)
			return true
		}
		return false
	})
}
func WithGetGetStrategy[K comparable, V any](getStrategy GetStrategy[K, V]) trcache.GetOption {
	return trcache.GetOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case getOptions[K, V]:
			opt.OptGetStrategy(getStrategy)
			return true
		}
		return false
	})
}
func WithGetSetOptions[K comparable, V any](options ...trcache.SetOption) trcache.GetOption {
	return trcache.GetOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case getOptions[K, V]:
			opt.OptSetOptions(options...)
			return true
		}
		return false
	})
}
func WithSetSetStrategy[K comparable, V any](setStrategy SetStrategy[K, V]) trcache.SetOption {
	return trcache.SetOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case setOptions[K, V]:
			opt.OptSetStrategy(setStrategy)
			return true
		}
		return false
	})
}
func WithDeleteDeleteStrategy[K comparable, V any](deleteStrategy DeleteStrategy[K, V]) trcache.DeleteOption {
	return trcache.DeleteOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case deleteOptions[K, V]:
			opt.OptDeleteStrategy(deleteStrategy)
			return true
		}
		return false
	})
}

type rootOptionBuilder[K comparable, V any] struct {
	trcache.RootOptionBuilderBase
}

func RootOpt[K comparable, V any]() *rootOptionBuilder[K, V] {
	return &rootOptionBuilder[K, V]{}
}
func (ob *rootOptionBuilder[K, V]) WithRefreshFunc(refreshFunc trcache.CacheRefreshFunc[K, V]) *rootOptionBuilder[K, V] {
	ob.AppendOptions(WithRefreshFunc[K, V](refreshFunc))
	return ob
}
func (ob *rootOptionBuilder[K, V]) WithSetPreviousOnGet(setPreviousOnGet bool) *rootOptionBuilder[K, V] {
	ob.AppendOptions(WithSetPreviousOnGet[K, V](setPreviousOnGet))
	return ob
}

type getOptionBuilder[K comparable, V any] struct {
	trcache.GetOptionBuilderBase
}

func GetOpt[K comparable, V any]() *getOptionBuilder[K, V] {
	return &getOptionBuilder[K, V]{}
}
func (ob *getOptionBuilder[K, V]) WithGetGetStrategy(getStrategy GetStrategy[K, V]) *getOptionBuilder[K, V] {
	ob.AppendOptions(WithGetGetStrategy[K, V](getStrategy))
	return ob
}
func (ob *getOptionBuilder[K, V]) WithGetSetOptions(options ...trcache.SetOption) *getOptionBuilder[K, V] {
	ob.AppendOptions(WithGetSetOptions[K, V](options...))
	return ob
}

type setOptionBuilder[K comparable, V any] struct {
	trcache.SetOptionBuilderBase
}

func SetOpt[K comparable, V any]() *setOptionBuilder[K, V] {
	return &setOptionBuilder[K, V]{}
}
func (ob *setOptionBuilder[K, V]) WithSetSetStrategy(setStrategy SetStrategy[K, V]) *setOptionBuilder[K, V] {
	ob.AppendOptions(WithSetSetStrategy[K, V](setStrategy))
	return ob
}

type deleteOptionBuilder[K comparable, V any] struct {
	trcache.DeleteOptionBuilderBase
}

func DeleteOpt[K comparable, V any]() *deleteOptionBuilder[K, V] {
	return &deleteOptionBuilder[K, V]{}
}
func (ob *deleteOptionBuilder[K, V]) WithDeleteDeleteStrategy(deleteStrategy DeleteStrategy[K, V]) *deleteOptionBuilder[K, V] {
	ob.AppendOptions(WithDeleteDeleteStrategy[K, V](deleteStrategy))
	return ob
}

type rootOptionsImpl[K comparable, V any] struct {
	trcache.IsRootOptionsImpl
	callDefaultDeleteOptions []trcache.DeleteOption
	callDefaultGetOptions    []trcache.GetOption
	callDefaultSetOptions    []trcache.SetOption
	name                     string
	refreshFunc              trcache.CacheRefreshFunc[K, V]
	setPreviousOnGet         bool
}

var _ options[string, string] = &rootOptionsImpl[string, string]{}

func (o *rootOptionsImpl[K, V]) OptCallDefaultDeleteOptions(options ...trcache.DeleteOption) {
	o.callDefaultDeleteOptions = options
}
func (o *rootOptionsImpl[K, V]) OptCallDefaultGetOptions(options ...trcache.GetOption) {
	o.callDefaultGetOptions = options
}
func (o *rootOptionsImpl[K, V]) OptCallDefaultSetOptions(options ...trcache.SetOption) {
	o.callDefaultSetOptions = options
}
func (o *rootOptionsImpl[K, V]) OptName(name string) {
	o.name = name
}
func (o *rootOptionsImpl[K, V]) OptRefreshFunc(refreshFunc trcache.CacheRefreshFunc[K, V]) {
	o.refreshFunc = refreshFunc
}
func (o *rootOptionsImpl[K, V]) OptSetPreviousOnGet(setPreviousOnGet bool) {
	o.setPreviousOnGet = setPreviousOnGet
}

type getOptionsImpl[K comparable, V any] struct {
	trcache.IsGetOptionsImpl
	customOptions []interface{}
	getStrategy   GetStrategy[K, V]
	setOptions    []trcache.SetOption
}

var _ getOptions[string, string] = &getOptionsImpl[string, string]{}

func (o *getOptionsImpl[K, V]) OptCustomOptions(customOptions []interface{}) {
	o.customOptions = customOptions
}
func (o *getOptionsImpl[K, V]) OptGetStrategy(getStrategy GetStrategy[K, V]) {
	o.getStrategy = getStrategy
}
func (o *getOptionsImpl[K, V]) OptSetOptions(options ...trcache.SetOption) {
	o.setOptions = options
}

type setOptionsImpl[K comparable, V any] struct {
	trcache.IsSetOptionsImpl
	duration    time.Duration
	setStrategy SetStrategy[K, V]
}

var _ setOptions[string, string] = &setOptionsImpl[string, string]{}

func (o *setOptionsImpl[K, V]) OptDuration(duration time.Duration) {
	o.duration = duration
}
func (o *setOptionsImpl[K, V]) OptSetStrategy(setStrategy SetStrategy[K, V]) {
	o.setStrategy = setStrategy
}

type deleteOptionsImpl[K comparable, V any] struct {
	trcache.IsDeleteOptionsImpl
	deleteStrategy DeleteStrategy[K, V]
}

var _ deleteOptions[string, string] = &deleteOptionsImpl[string, string]{}

func (o *deleteOptionsImpl[K, V]) OptDeleteStrategy(deleteStrategy DeleteStrategy[K, V]) {
	o.deleteStrategy = deleteStrategy
}
